### ISSUE TITLE
Support for 'typed-redux-saga/macro' ?

### ISSUE THREAD

**Issue by osmestad** [jambit/eslint-plugin-typed-redux-saga#2]
Nice plugin!

Only thing I could wish for would be support for importing from 'typed-redux-saga/macro' and enforcing that :-)

**Comment by SantoJambit** [comment]
Sorry about the delay. I never got any  emails for this project, possibly, because It wasn't starred? I only noticed because I was mentioned in another issue.

On the topic: I am quite busy today, but I'll try to find some time to take a first look in the next couple of days.

**Comment by SantoJambit** [comment]
Since I have not used the macros before, I just want to confirm what the plugin should do:
It should work exactly the same as `@jambit/typed-redux-saga/use-typed-effects`, but should use the /macro path instead?

I'll look into adding options to that rule. Should be straight forward I hope.

**Comment by SantoJambit** [comment]
Version 0.3.0 adds support for this. Please give it a try (see the updated readme on how to configure the rule).

**Comment by osmestad** [comment]
Works beautifully, thank you!

(Sorry for the slow reply!)
